# syntax=docker/dockerfile:1
FROM public.ecr.aws/lambda/python:3.13

COPY mast_transfer_tools mast_transfer_tools
COPY pyproject.toml .
RUN pip install -e .

ENV PYTHONUNBUFFERED=1
CMD [ "mast_transfer_tools.lambda_.core.main" ]
