"""Helper functions for implementing a command line interface.

Functions in this file named 'require_<thing>' check preconditions
which, if violated, indicate user error (some variation on the theme
of having mistyped a command).  They either silently succeed, or
print a human-readable error message and exit the program.

Functions in this file named 'fatal_<thing>' report various kinds
of fatal errors.  They always exit the program.
"""

import logging
import os
import sys

from contextlib import contextmanager
from pathlib import Path
from io import BufferedRandom
from tempfile import mkstemp
from typing import Iterator, NoReturn, Any

from botocore.exceptions import ClientError
# click's colored output support does not respect TERM or NO_COLOR
# so we're not gonna use it until they fix that
from click import format_filename
from hostess.aws.s3 import Bucket
from pandas import DataFrame
from yaml import YAMLError, MarkedYAMLError

import mast_transfer_tools.validation
from mast_transfer_tools.labels import Label, STANDARDS_SUPPORTING_DATA_VALIDATION

from typing import Literal, TYPE_CHECKING


def configure_logging(level: int) -> None:
    """
    Configure the `logging` module appropriately for MTT CLI programs.
    """
    logging.basicConfig(
        level = level,
        # TODO message formatting etc
    )
    logging.captureWarnings(True)  # NOQA: FBT003


def require_directory(dir: Path) -> None:
    """
    Command line validation: require 'dir' to be an existing directory.
    """

    if not dir.is_dir():
        sys.stderr.write(
            f"{format_filename(dir)}: error: Not a directory\n"
        )
        sys.exit(1)


def require_bucket(bucket: "Bucket") -> None:
    """
    Command line validation: require 'bucket' to be an existing S3 bucket.
    """

    from botocore.exceptions import ClientError

    try:
        _ = bucket.bucket_type
    except ClientError as ce:
        # can't type-check against this because it's dynamically generated by
        # botocore errorfactory
        if type(ce).__name__ == "NoSuchBucket":
            sys.stderr.write(f"{bucket.name}: error: No such bucket\n")
            sys.exit(1)
        # other failures like permissions, connectivity, etc. are not our
        # problem at this step


def parse_src_url_arg(
    arg: Path | str
) -> tuple[Literal[None], Path] | tuple["Bucket", str]:
    """If ARG is a path, or a string that looks like a local pathname,
    check that it's a directory that exists, then return `(None, Path(arg))`.
    Otherwise, if it's a string that looks like 's3://<bucket-name>[/<prefix>]',
    refers to a bucket that exists, then return `(bucket, prefix)`
    where `bucket` is a hostess.aws.s3.Bucket object referring to the bucket,
    and `prefix` is the specified prefix, if any.

    More URL schemes may be added in the future, in which case the return
    value will turn into a more structured object.  To leave space for this
    possibility, it is an error if 'arg' is a string that starts with any
    sequence of ASCII alphanumerics followed by '://'.
    """
    if not isinstance(arg, Path):
        if (p := arg.find("://")) >= 0:
            schema = arg[:p].upper()
            if schema == "S3":
                from hostess.aws.s3 import Bucket
                bucket_name, _, prefix = arg[(p+3):].partition("/")
                bucket = Bucket(bucket_name)
                require_bucket(bucket)
                prefix = prefix.strip("/")
                if prefix:
                    prefix += "/"
                return (bucket, prefix)

            raise ValueError(f"{schema} URLs are not supported")

        arg = Path(arg)
    require_directory(arg)
    return (None, arg)


def require_no_label_errors(label: Label, label_file: Path) -> None:
    """
    Require 'label' to have no errors.  If it does have errors,
    report them and exit.
    """
    errors = label.errors
    if not errors:
        return

    sys.stderr.write(f"Errors found in {label_file}:\n")
    for lpath, problems in sorted(errors.items()):
        match len(problems):
            case 0:
                pass
            case 1:
                sys.stderr.write(f"  key {lpath}: {problems[0]}\n")
            case _:
                sys.stderr.write(f"  key {lpath}:\n")
                for p in problems:
                    sys.stderr.write(f"    {p}\n")
    sys.exit(1)


def fatal_oserror(e: OSError, operation: str = "") -> NoReturn:
    """
    Report an OSError which prevents the command from continuing any
    further.  Does not return.

    The message printed takes one of several traditional forms depending
    on the contents of 'e' and whether 'operation' is nonempty.
    """
    reason = e.strerror
    if e.filename:
        subject = format_filename(e.filename)
    else:
        subject = format_filename(sys.argv[0], shorten=True)

    if e.filename2:
        target = format_filename(e.filename2)
    else:
        target = ""

    if operation and target:
        msg = f"{subject}: error: {operation} to {target}: {reason}\n"
    elif operation and not target:
        msg = f"{subject}: error: {operation}: {reason}\n"
    elif target and not operation:
        msg = f"{subject} and {target}: error: {reason}\n"
    else:
        msg = f"{subject}: error: {reason}\n"

    sys.stderr.write(msg)
    sys.exit(1)


def fatal_yaml_error(e: YAMLError, yaml_file: Path) -> NoReturn:
    """
    Report a YAML parser error which prevents the command from continuing
    any further.  Does not return.
    """
    subject = format_filename(yaml_file)
    msglines = [f"YAML syntax error while reading {subject}:\n"]
    if isinstance(e, MarkedYAMLError):
        if (
            e.context_mark is not None
            and e.context_mark.name in ("<unicode string>", "<byte string>")
        ):
            e.context_mark.name = subject
        if (
            e.problem_mark is not None
            and e.problem_mark.name in ("<unicode string>", "<byte string>")
        ):
            e.problem_mark.name = subject

    msglines.extend(
        f"|  {line}\n"
        for line in str(e).splitlines()
    )

    sys.stderr.write("".join(msglines))
    sys.exit(1)


@contextmanager
def atomic_update(path: str | Path) -> Iterator[BufferedRandom]:
    """
    Atomically update a file.  Use as a context manager:

        with atomic_update(path) as fp:
            fp.write(new_file_contents)

    When the context is exited normally, the file at `path` will
    be updated atomically with the new contents written to `fp`;
    if it didn't already exist, it will be created at that point.

    If an exception is thrown out of the with-block, `path` will
    be unchanged; if it didn't already exist, it will continue to
    not exist.

    The stream 'fp' is always opened for reading and writing,
    in binary mode. If you want text mode, wrap 'fp' in a TextIOWrapper
    (you probably should set write_through=True on the TextIOWrapper).
    """
    # TODO: This is the standard algorithm for atomic file update on Unix.
    # Something different needs to be done on Windows and I don't know
    # what that something is.

    if not isinstance(path, Path):
        path = Path(path)

    (fd, tmppath) = mkstemp(
        prefix=path.stem + ".",
        suffix=".new",
        dir=path.parent
    )
    try:
        fp = open(fd, "w+b", closefd=False) # noqa: SIM115
        yield fp
        fp.close()
        os.fsync(fd)
        os.rename(tmppath, path)
        # technically we ought to fsync the containing _directory_ at
        # this point but it's unlikely to matter

    except:
        os.unlink(tmppath)
        raise

    finally:
        os.close(fd)


def require_index(index_file: Path) -> DataFrame:
    import pandas as pd

    try:
        table = pd.read_csv(index_file)
        print(table)
        assert "path" in table.columns
    except FileNotFoundError:
        sys.stderr.write(f"{index_file} not found.")
        sys.exit(1)
    except Exception as ex:
        sys.stderr.write(
            f"{ex}: error: index must be a CSV file with a column named "
            f"'path'.\n"
        )
        sys.exit(1)
    return table


def _format_validation_failures(
    failures: Any, *, indent: int = 0
) -> list[str]:
    pad = " " * indent

    if isinstance(failures, dict):
        lines = []
        for key, value in failures.items():
            lines.append(f"{pad}{key}")
            lines.extend(
                _format_validation_failures(value, indent=indent + 2)
            )
        return lines

    if isinstance(failures, list):
        lines = []
        for item in failures:
            lines.extend(_format_validation_failures(item, indent=indent))
        return lines

    return [f"{pad}{failures}"]


def validate_chatty(
    file: str,
    parsed_label: Label,
    bucket_name: str | None = None,
    *,
    object_check_hook: bool = True
) -> tuple[str, bool]:
    filetypes = parsed_label.filetypes_for_filename(file)

    if len(filetypes) == 0:
        return "no filename patterns in label match", False

    if len(filetypes) > 1:
        return (
            f"Ambiguous filetype. matches "
            f"{', '.join(n for n in filetypes.keys())}"
        ), False

    ft = list(filetypes.values())[0]
    if ft.standard not in STANDARDS_SUPPORTING_DATA_VALIDATION:
        return (
            f"pass by default ({ft.standard} does not support "
            f"data-level validation)"
        ), True

    import mast_transfer_tools.validation

    try:
        failures = mast_transfer_tools.validation.validate(
            ft, file, bucket=bucket_name, object_check_hook=object_check_hook
        )
    except ClientError as ce:
        raise OSError(
            f"{ce}. If this represents a permissions error, note that your "
            f"default system AWS account must have appropriate permissions to "
            f"{bucket_name}."
        )

    if len(failures) == 0:
        return "", True

    return "\n" + "\n".join(
        _format_validation_failures(failures, indent=2)
    ), False


def require_valid_targets(
    source: Path | Bucket, table: DataFrame
) -> list[Path | str]:
    if isinstance(source, Path):
        targets = [source / f for f in table['path']]
        missing = [t for t in targets if not t.exists()]
    else:
        targets = [f for f in table['path']]
        heads = source.head(targets)
        # NOTE: it's best to validate the caller's ability to access the
        #  bucket at all prior to calling this function, or the failure message
        #  could be misleading
        missing = [
            t for t, h in zip(heads, targets) if isinstance(h, Exception)
        ]
    if len(missing) > 0:
        sys.stderr.write(f"not found:\n{'\n'.join(missing)}")
        sys.exit(1)
    return targets


def calc_checksums_with_progress(targets: list[Path | Any]) -> list[Any]:
    from hostess.aws.utilities import crc32_base64
    from rich.progress import Progress

    checksums = []
    with Progress() as progress:
        task = progress.add_task(
            "Calculating checksums...", total=len(targets)
        )
        for t in targets:
            checksums.append(crc32_base64(t))
            progress.update(task, advance=1)
    return checksums
