name: Lint and test
on: [ push ]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -   name: Check out code
                uses: actions/checkout@v6

            # This step should install the *oldest* version of Python
            # supported by this package.
            -   name: Set up Python 3.11
                uses: actions/setup-python@v6
                id: py
                with:
                    python-version: '3.11'
                    cache: 'pip'

            -   name: Ruff lints
                uses: astral-sh/ruff-action@v4.0.0
                with:
                    version: "latest"
    unit-tests:
        runs-on: ubuntu-latest
        strategy:
            # Test on all released Pythons starting with the
            # oldest one that's supported.
            matrix:
                python-version: ['3.11', '3.12', '3.13', '3.14']
        steps:
            - name: Check out code
              uses: actions/checkout@v6

            - name: Set up Python
              uses: actions/setup-python@v6
              id: py
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: 'pip'

            - name: Install dependencies
              shell: bash
              run: |
                  set -euo pipefail
                  echo ::group::Creating virtualenv...
                  export PIP_DISABLE_PIP_VERSION_CHECK=1
                  ${{ steps.py.outputs.python-path }} -m venv .pytest-venv
                  source .pytest-venv/bin/activate
                  echo ::endgroup::

                  echo ::group::Installing project dependencies...
                  pip install -e '.[tests]'
                  echo ::endgroup::

            - name: Unit tests
              shell: bash
              run: |
                  source .pytest-venv/bin/activate
                  pytest -v -Werror
